version: "3.8"

services:
  client:
    build: ./client
    ports:
      - 8080:8080
    volumes:
      - ./client:/client-app

  api:
    build: ./api
    ports:
      - 3000:3000
    volumes:
      - ./api:/api
    depends_on:
      - db
  
  db:
    image: postgres
    env_file: ./database  .env