version: "3"

services:
  client:
    build: ./client
    ports:
      - 8080:8080
    volumes:
      - ./client:/app-client
      - ./client/node_modules:/app-client/node_modules
    command: bash -c "yarn install && yarn dev"

  api:
    build: ./api
    ports:
      - 3000:3000
    volumes:
      - ./api:/api
    depends_on:
      - db
  
  db:
    image: postgres
    env_file: ./database.env